# Generated by Django 5.2.2 on 2025-06-24 23:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='blog',
            new_name='blog_id',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'blog_id')},
        ),
    ]
