# Generated by Django 5.2.2 on 2025-09-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmedia',
            name='file',
            field=models.FileField(upload_to='django/blog_api'),
        ),
    ]
