# Generated by Django 5.2.2 on 2025-09-29 20:52

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_blogmedia_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmedia',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='django/blog_api'),
        ),
    ]
